[project]
name = "word-vector-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "loguru>=0.7.3",
    "omegaconf>=2.3.0",
    "torch>=2.9.1",
    "tqdm>=4.67.1",
]
